spring:
  application:
    name: bookABatterySERVICE4EUREKA
  
server:
  port: 7111
  
eureka:
  password: password
  client:
    serviceUrl:
      defaultZone: http://user:${eureka.password}@localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
